<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>print_workflow</name>
  <version>1.0.0</version>
  <description>Print workflow GUI for controlling three XYT300 motors simultaneously</description>
  <maintainer email="yang@example.com">yang</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>

  <exec_depend>python3-pyqt5</exec_depend>

  <exec_depend>xyt300_motor</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
